add_library(libSceBluetoothHid SHARED EXCLUDE_FROM_ALL Export.cpp)
target_include_directories(libSceBluetoothHid PRIVATE ${LIBS_INCLUDE_DIR})
configure_windows_unwind(libSceBluetoothHid)

if(BUILD_TESTING)
    add_test_executable(guest_bluetooth_hid_tests ${LIBS_INCLUDE_DIR}/tests/GuestBluetoothHid.cpp)
    target_include_directories(guest_bluetooth_hid_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_bluetooth_hid_tests PRIVATE libSceBluetoothHid libc)
    configure_windows_unwind(guest_bluetooth_hid_tests)
    add_test(NAME guest_bluetooth_hid COMMAND guest_bluetooth_hid_tests)
    if(WIN32)
        set_tests_properties(guest_bluetooth_hid PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libSceBluetoothHid>")
    endif()
endif()
